from tkinter import *
def intro(lost):
    root = Tk()
    root.overrideredirect(True)
    root.geometry("{0}x{1}+0+0".format(root.winfo_screenwidth(), root.winfo_screenheight()))
    snake_label = Label(root, text='Snake', font=('Calibri', 124), anchor='center')
    snake_label.grid(column=1, row=0)
    def start_game():
        root.destroy()
    if lost == True:
        lost_label = Label(root, text='You Lost!', font=('Calibri', 30), fg='red')
        lost_label.grid(column=1, row=1)
    play_button = Button(root, text='Play', height=10, width=20, bg='green', fg='white', command=start_game)
    play_button.grid(column=0, row=5)
    quit_button = Button(root, text='Stop', height=10, width=20, bg='red', fg='white', command=quit)
    quit_button.grid(column=2, row=5)
    root.grid_columnconfigure(0, weight=1)
    root.grid_columnconfigure(1, weight=1)
    root.grid_columnconfigure(2, weight=1)
    root.grid_rowconfigure(0, weight=1)
    root.grid_rowconfigure(1, weight=1)
    root.grid_rowconfigure(2, weight=1)
    root.grid_rowconfigure(3, weight=1)
    root.grid_rowconfigure(4, weight=1)
    root.grid_rowconfigure(5, weight=1)
    root.grid_rowconfigure(6, weight=1)
    root.grid_rowconfigure(7, weight=1)
    root.grid_rowconfigure(8, weight=1)
    root.protocol('WM_DELETE_WINDOW', quit)
    root.mainloop()
